application: foodie
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi.*
  script: main.service

- url: /stylesheets
  static_dir: stylesheets
  
- url: /images
  static_dir: images
 
- url: /javascript
  static_dir: javascript

- url: / 
  upload: index.html
  static_files: index.html

- url: /.*
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest